# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    initrd = {
      luks.devices."drv".device = "/dev/disk/by-uuid/f8f2adb7-6f21-4f38-b659-d38435487e1d";
      availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
      kernelModules = [ ];
    };
    plymouth.enable = true;
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
    kernelParams = [ "resume_offset=47517297" ];
    resumeDevice = "/dev/disk/by-uuid/5f412f9a-4adb-4b64-809b-43dd099fa601";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5f412f9a-4adb-4b64-809b-43dd099fa601";
    fsType = "btrfs";
    options = [ "relatime" ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/5f412f9a-4adb-4b64-809b-43dd099fa601";
    fsType = "btrfs";
    options = [ "subvol=swap" "noatime" ];
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7EB2-92E8";
      fsType = "vfat";
    };

  swapDevices = [ {
    device = "/swap/swapfile";
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  services.auto-cpufreq = {
    enable = true;
    settings = {
      battery = {
        governor = "powersave";
        turbo = "never";
      };
      charger = {
       governor = "performance";
       turbo = "auto";
      };
    };
  };
}
